// Code generated by Kitex v1.4.3. DO NOT EDIT.

package frontier

import (
	"context"
	"github.com/volcengine/VolcEngineRTC/server/video_conf_control/kitex_gen/rtc_frontier"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushToClient(ctx context.Context, param *rtc_frontier.TPushParam, callOptions ...callopt.Option) (r *rtc_frontier.TPushResp, err error)
	BroadcastToClient(ctx context.Context, param *rtc_frontier.TBroadCastParam, callOptions ...callopt.Option) (r *rtc_frontier.TBroadCastResp, err error)
	CloseClient(ctx context.Context, param *rtc_frontier.TCloseClientParam, callOptions ...callopt.Option) (r *rtc_frontier.TCloseClientResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(psm string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(psm))

	config := byted.NewClientConfig()
	config.DestService = psm

	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFrontierClient{
		kClient: newServiceClient(kc),
	}, nil
}

// NewClientWithBytedConfig creates a client for the service defined in IDL.
func NewClientWithBytedConfig(psm string, config *byted.ClientConfig, opts ...client.Option) (Client, error) {
	if config == nil {
		config = byted.NewClientConfig()
	}
	config.DestService = psm

	var options []client.Option
	options = append(options, client.WithDestService(psm))

	options = append(options, byted.ClientSuiteWithConfig(serviceInfo(), config))
	options = append(options, opts...)
	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFrontierClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(psm string, opts ...client.Option) Client {
	kc, err := NewClient(psm, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

// MustNewClientWithBytedConfig creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClientWithBytedConfig(psm string, config *byted.ClientConfig, opts ...client.Option) Client {
	kc, err := NewClientWithBytedConfig(psm, config, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFrontierClient struct {
	*kClient
}

func (p *kFrontierClient) PushToClient(ctx context.Context, param *rtc_frontier.TPushParam, callOptions ...callopt.Option) (r *rtc_frontier.TPushResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushToClient(ctx, param)
}

func (p *kFrontierClient) BroadcastToClient(ctx context.Context, param *rtc_frontier.TBroadCastParam, callOptions ...callopt.Option) (r *rtc_frontier.TBroadCastResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.BroadcastToClient(ctx, param)
}

func (p *kFrontierClient) CloseClient(ctx context.Context, param *rtc_frontier.TCloseClientParam, callOptions ...callopt.Option) (r *rtc_frontier.TCloseClientResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CloseClient(ctx, param)
}
