// Code generated by Kitex v1.4.3. DO NOT EDIT.

package frontier

import (
	"context"
	"github.com/volcengine/VolcEngineRTC/server/video_conf_control/kitex_gen/rtc_frontier"
)

func serviceInfo() *kitex.ServiceInfo {
	return frontierServiceInfo
}

var frontierServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "Frontier"
	handlerType := (*rtc_frontier.Frontier)(nil)
	methods := map[string]kitex.MethodInfo{
		"push_to_client":      kitex.NewMethodInfo(pushToClientHandler, newFrontierPushToClientArgs, newFrontierPushToClientResult, false),
		"broadcast_to_client": kitex.NewMethodInfo(broadcastToClientHandler, newFrontierBroadcastToClientArgs, newFrontierBroadcastToClientResult, false),
		"close_client":        kitex.NewMethodInfo(closeClientHandler, newFrontierCloseClientArgs, newFrontierCloseClientResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "rtc_frontier",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v1.4.3",
		Extra:           extra,
	}
	return svcInfo
}

func pushToClientHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rtc_frontier.FrontierPushToClientArgs)
	realResult := result.(*rtc_frontier.FrontierPushToClientResult)
	success, err := handler.(rtc_frontier.Frontier).PushToClient(ctx, realArg.Param)
	if err != nil {
		switch v := err.(type) {
		case *rtc_frontier.UserException:
			realResult.UserException = v
		case *rtc_frontier.UnknownException:
			realResult.UnknownException = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newFrontierPushToClientArgs() interface{} {
	return rtc_frontier.NewFrontierPushToClientArgs()
}

func newFrontierPushToClientResult() interface{} {
	return rtc_frontier.NewFrontierPushToClientResult()
}

func broadcastToClientHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rtc_frontier.FrontierBroadcastToClientArgs)
	realResult := result.(*rtc_frontier.FrontierBroadcastToClientResult)
	success, err := handler.(rtc_frontier.Frontier).BroadcastToClient(ctx, realArg.Param)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newFrontierBroadcastToClientArgs() interface{} {
	return rtc_frontier.NewFrontierBroadcastToClientArgs()
}

func newFrontierBroadcastToClientResult() interface{} {
	return rtc_frontier.NewFrontierBroadcastToClientResult()
}

func closeClientHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*rtc_frontier.FrontierCloseClientArgs)
	realResult := result.(*rtc_frontier.FrontierCloseClientResult)
	success, err := handler.(rtc_frontier.Frontier).CloseClient(ctx, realArg.Param)
	if err != nil {
		switch v := err.(type) {
		case *rtc_frontier.UserException:
			realResult.UserException = v
		case *rtc_frontier.UnknownException:
			realResult.UnknownException = v
		default:
			return err
		}
	} else {
		realResult.Success = success
	}
	return nil
}
func newFrontierCloseClientArgs() interface{} {
	return rtc_frontier.NewFrontierCloseClientArgs()
}

func newFrontierCloseClientResult() interface{} {
	return rtc_frontier.NewFrontierCloseClientResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PushToClient(ctx context.Context, param *rtc_frontier.TPushParam) (r *rtc_frontier.TPushResp, err error) {
	var _args rtc_frontier.FrontierPushToClientArgs
	_args.Param = param
	var _result rtc_frontier.FrontierPushToClientResult
	if err = p.c.Call(ctx, "push_to_client", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.UserException != nil:
		return r, _result.UserException
	case _result.UnknownException != nil:
		return r, _result.UnknownException
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) BroadcastToClient(ctx context.Context, param *rtc_frontier.TBroadCastParam) (r *rtc_frontier.TBroadCastResp, err error) {
	var _args rtc_frontier.FrontierBroadcastToClientArgs
	_args.Param = param
	var _result rtc_frontier.FrontierBroadcastToClientResult
	if err = p.c.Call(ctx, "broadcast_to_client", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) CloseClient(ctx context.Context, param *rtc_frontier.TCloseClientParam) (r *rtc_frontier.TCloseClientResp, err error) {
	var _args rtc_frontier.FrontierCloseClientArgs
	_args.Param = param
	var _result rtc_frontier.FrontierCloseClientResult
	if err = p.c.Call(ctx, "close_client", &_args, &_result); err != nil {
		return
	}
	switch {
	case _result.UserException != nil:
		return r, _result.UserException
	case _result.UnknownException != nil:
		return r, _result.UnknownException
	}
	return _result.GetSuccess(), nil
}
