// this file is generated by build_framework.sh on CI. Do not change it manually
static NSString const *ByteRtcEngine_Version = @"3.20.101";
static NSString const *ByteRtcEngine_CID = @"258377c81fbcc8a41f6cd77e944a19f41a7c750c";
