// this file is generated by build_framework.sh on CI. Do not change it manually
static NSString const *ByteRtcEngine_Version = @"3.19.205";
static NSString const *ByteRtcEngine_CID = @"add01498875afb56e420e18eed19f25866f9e3a6";
